// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqojdjmgfairvddgeutz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxb2pkam1nZmFpcnZkZGdldXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzAwNzcsImV4cCI6MjA2MzMwNjA3N30.fiJart0AzOc0w8pLavFR_jq_uLxw6-ZmNULyAAColk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);